# -*- encoding: utf-8 -*-

=begin
#PluralKit

#This is the API for [PluralKit](https://pluralkit.me/)! :)  The API itself is stable, but this document (the OpenAPI description) is still subject to change, and may be updated, corrected or restructured in the future (as long as it's still coherent with the real API).  # Authentication Authentication is handled using a \"system token\". At the moment, the only way to obtain a system token is to use the `pk;token` command through the Discord bot.  This will generate an opaque string you must pass as the `Authorization` header to API requests. Many API endpoints are available anonymously, but most of them will hide information from  unauthenticated requests to align with the relevant privacy settings.  # Errors Errors are just returned as HTTP response codes. Most error responses include a human-readable error message as the body, but this should not be relied on. Just read the response codes :)  # OpenAPI version history - **1.1**: Granular member privacy - **1.0**: (initial definition version) 

The version of the OpenAPI document: 1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "pluralkit-api/version"

Gem::Specification.new do |s|
  s.name        = "pluralkit-api"
  s.version     = PluralKitAPI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Anna Kudriavtsev"]
  s.email       = ["anna328p@gmail.com"]
  s.homepage    = "https://github.com/anna328p/ruby-pluralkit-api"
  s.summary     = "API client for PluralKit"
  s.description = "A client for the PluralKit REST API"
  s.license     = "AGPL-3.0-or-later"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
